from scripts.common import parse_samples_and_reads,parse_sample_genome_and_sequences,parse_metadata

configfile: os.path.join(workflow.basedir, "..", "config", "config.yaml")

# path to sample and reads info
SAMPLE_INFO = config["sample_info"]

# directory to raw reads
READDIR = config["reads_dir"]

# directory to genome sequences
GENOMEDIR = config["genome_dir"]

# directory to prophage prediction results
PROPHAGEDIR = config["prophage_dir"]

# directory to save the results
RESULTS_DIR = config["results_dir"]

SAMPLE, R1_MAP, R2_MAP, SAMPLE_GENOME_MAP, GENOME, GENOME_SEQUENCE_MAP = parse_metadata(SAMPLE_INFO, READDIR, GENOMEDIR, PROPHAGEDIR)

# function to define wildcards
def expand_all(pattern):
    return expand(pattern, sample = SAMPLE, genome=GENOME)

# rules
include: "rules/setup.smk"
include: "rules/trimming.smk"
include: "rules/mapping.smk"
include: "rules/assembly.smk"
include: "rules/alignment.smk"
include: "rules/annotation.smk"

# funtion to define requested inputs for the rule all
def get_all_input(wildcards):
    wanted_input = []

    if config["step"] == "fastqc":
        wanted_input = fastqc_input
    
    if config["step"] == "trimming":
        wanted_input = trimming_input

    if config["step"] == "mapping":
        wanted_input += trimming_input
        wanted_input += mapping_input
        
    if config["step"] == "assemble":
        wanted_input += trimming_input
        wanted_input += assembly_input

    if config["step"] == "alignment":
        wanted_input += trimming_input
        wanted_input += assembly_input
        wanted_input += alignment_input
    
    if config["step"] == "annotation":
        wanted_input += trimming_input
        wanted_input += assembly_input
        wanted_input += annotation_input
    
    if config["step"] == "all":
        wanted_input = all_input

    return wanted_input

# master target rule
rule all:
    input: get_all_input
